# Generated by Django 3.0.7 on 2020-06-11 13:21

import apps.post.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True, verbose_name='link')),
                ('imagem_destaque', models.ImageField(upload_to=apps.post.models.upload_directory_path)),
                ('texto', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('autor', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
