# Generated by Django 3.0.7 on 2020-06-17 14:03

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='texto',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
