# Generated by Django 3.0.7 on 2020-06-11 13:54

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('post', '0002_post_destaque'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': '-created_at', 'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='core.Tag', to='core.TagWithHits', verbose_name='Tags'),
        ),
    ]
