# Generated by Django 3.0.7 on 2020-06-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200611_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lerd',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
