# Generated by Django 3.0.7 on 2020-06-11 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagwithhits',
            options={'ordering': ['hits']},
        ),
    ]
