# Generated by Django 3.0.7 on 2020-06-18 21:48

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to=apps.core.models.upload_directory_path),
        ),
    ]
